@FirstAPI_HostAddress = http://localhost:5000
@rootURL = http://localhost:5000

// http://localhost:5000/WeatherForecast


GET {{FirstAPI_HostAddress}}/weatherforecast/
Accept: application/json



###
GET {{rootURL}}/api/books
Accept: application/json
// To get all books



###
GET {{rootURL}}/api/books/2
Accept: application/json
// To get a specific book by ID




###
POST {{rootURL}}/api/books
Content-Type: application/json
// TO add a new book with Details except Id.
{
   "Title": "Mediation",
   "Author": "Marcus",
   "YearPublished": 2015
}



###
PUT {{rootURL}}/api/books/5
Content-Type: application/json
// To update a specific book by ID
{
   "Id":5,
   "Title": "Meditations",
   "Author": "Marcus Aurelius",
   "YearPublished": 2007
}




###
DELETE {{rootURL}}/api/books/8
// To Delete a specific book by ID



###
POST {{rootURL}}/api/books
Content-Type: application/json
{
   "Title": "Bhagvat Gita",
   "Author": "Ved Vyasa",
   "YearPublished": 400
}

###
POST {{rootURL}}/api/books
Content-Type: application/json
{
   "Title": "7 Habits of Highly Affective People",
   "Author": "Stephen R. Convey",
   "YearPublished": 1989
}